### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by johann-petrak** [bobbylight/RSTAUI#4]
Running "gradle jar" on either the latest checked out git version or the latest release version (2.5.4) produces a large number of errors (symbol not found, package does not exist etc.)

**Comment by bobbylight** [comment]
This project depends on the RSyntaxTextArea and AutoComplete sister projects having been built along-side it - see the `compileJava` definition in `build.gradle`.  Perhaps there is a better way of handling this dependency in Gradle?  My goal was to allow myself (and others) to build this project locally without having to update dependencies every time one of the two sister projects it's dependent on changed.

Let me know if there's a better way to handle this (or a pull request to make it better is also welcome).  Otherwise I'll just close this ticket.

**Comment by johann-petrak** [comment]
Oh OK, I am sorry I did not realize this convention. Maybe the easiest thing would be to add an INSTALL.txt file that explains what is needed to build?
I usually assume that if there is only something like gradle or mvn without additional build instructions, that those things will handle whatever is needed.

**Comment by bobbylight** [comment]
There is (now) documentation in the readme.txt file in `src/main/dist`, but I admit that is not the optimal place.  I'll do as you suggest soon.  And again, if there's a better way to do what I'm trying to accomplish, I'm all ears!  I'm still pretty green with Gradle.
